version: 2.1

parameters:
  SOURCE_TYPE:
    type: string
    default: "github"
  S3_URL:
    type: string
    default: ""
  REPOSITORY:
    type: string
    default: "thales-markets/thales-sport-markets"
  REF:
    type: string
    default: "main"
  BUILD_DIR:
    type: string
    default: ""
  PACKAGE_INSTALL_COMMAND:
    type: string
    default: "export NODE_OPTIONS=--openssl-legacy-provider && npm install"
  BUILD_COMMAND:
    type: string
    default: "npm run build"
  OUTPUT_DIR:
    type: string
    default: "build"
  ONE_CLICK_SERVER_URL:
    type: string
    default: ""
  ENVIRONMENT_VARIABLES:
    type: string
    default: ""  # Base64 encoded

jobs:
  publish:
    docker:
      - image: cimg/node:current
    steps:
      # decode environment variables and store in workspace
      - run:
          name: Decode environment variables
          command: |
            echo "<< pipeline.parameters.ENVIRONMENT_VARIABLES >>" | base64 --decode > ~/project/.env
            cat ~/project/.env
      - when:
          condition:
            equal: ["github", "<< pipeline.parameters.SOURCE_TYPE >>"]
          steps:
            - run:
                name: Clone GitHub repository
                command: |
                  git clone "https://github.com/<< pipeline.parameters.REPOSITORY >>.git" ~/project/repository
                  if [ "<< pipeline.parameters.REF >>" != "main" ]; then
                    cd ~/project/repository
                    git checkout "<< pipeline.parameters.REF >>"
                  fi
      - when:
          condition:
            equal: ["s3", "<< pipeline.parameters.SOURCE_TYPE >>"]
          steps:
            - run:
                name: Download and Extract from S3
                command: |
                  curl "<< pipeline.parameters.S3_URL >>" -o package.zip
                  unzip package.zip -d ~/project/repository
      - run:
          name: Run build command
          working_directory: ~/project/repository
          command: |
            set -e  # Ensure that the script fails if any command fails
            source ~/project/.env

            # Navigate to the build directory if specified
            if [ -n "<< pipeline.parameters.BUILD_DIR >>" ]; then
              echo "Changing to build directory: << pipeline.parameters.BUILD_DIR >>"
              cd "<< pipeline.parameters.BUILD_DIR >>"
            else
              echo "No build directory specified, staying in repository root."
            fi

            # Run package install command if specified
            if [ -n "<< pipeline.parameters.PACKAGE_INSTALL_COMMAND >>" ]; then
              echo "Running package install command..."
              eval "<< pipeline.parameters.PACKAGE_INSTALL_COMMAND >>"
            else
              echo "No package install command specified."
            fi

            # Run build command
            echo "Running build command..."
            eval "<< pipeline.parameters.BUILD_COMMAND >>"

      - run:
          name: Create armada release
          working_directory: ~/project/repository
          command: |
            bundle_filename="$(npx --package=armada-cli@0.4.1 --yes armada bundle create armada-bundle << pipeline.parameters.OUTPUT_DIR >>)"
            checksum="$(npx --package=armada-cli@0.4.1 --yes armada bundle checksum $bundle_filename)"
            echo $checksum > checksum
            echo "Bundle Filename: $bundle_filename"
            echo "Checksum: $checksum"
        
      # store artifacts in circleci for download
      - store_artifacts:
          path: ~/project/repository/armada-bundle.tgz
      - store_artifacts:
          path: ~/project/repository/checksum
      - run:
          name: Notify one click server of new release
          command: |
            BUNDLE_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/armada-bundle.tgz"
            PIPELINE_ID="<< pipeline.id >>"
            CHECKSUM=$(cat ~/project/repository/checksum)
            ONE_CLICK_SERVER_URL="<< pipeline.parameters.ONE_CLICK_SERVER_URL >>"
            
            echo "Bundle URL: $BUNDLE_URL"
            echo "Pipeline ID: $PIPELINE_ID"
            echo "Checksum: $CHECKSUM"
            echo "One Click Server URL: $ONE_CLICK_SERVER_URL"

            FULL_URL="${ONE_CLICK_SERVER_URL}/circleci/notify"
            echo "Full URL: $FULL_URL"

            DATA='{"checksum": "'"$CHECKSUM"'", "bundleUrl": "'"$BUNDLE_URL"'", "pipelineId": "'"$PIPELINE_ID"'"}'
            echo "Data Payload: $DATA"

            curl -X POST -H "Content-Type: application/json" -d "$DATA" "$FULL_URL"


workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish
